name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: rustc version
      run: rustc --version
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run examples
      run: ./test.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: test.sh
